"""Add Channel, Message, Follow, Reaction, Notification tables and modify User table

Revision ID: 769d596e6c7e
Revises: 055e30a3ea0a
Create Date: 2025-11-25 23:40:21.279408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '769d596e6c7e'
down_revision: Union[str, Sequence[str], None] = '055e30a3ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_owner_id'), 'channel', ['owner_id'], unique=False)
    op.create_index(op.f('ix_channel_slug'), 'channel', ['slug'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('channelmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channelmember_channel_id'), 'channelmember', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channelmember_user_id'), 'channelmember', ['user_id'], unique=False)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_channel_id'), 'follow', ['channel_id'], unique=False)
    op.create_index(op.f('ix_follow_user_id'), 'follow', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('thread_root_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['thread_root_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_author_id'), 'message', ['author_id'], unique=False)
    op.create_index('ix_message_channel_id_created_at', 'message', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_message_parent_id', 'message', ['parent_id'], unique=False)
    op.create_index('ix_message_thread_root_id_created_at', 'message', ['thread_root_id', 'created_at'], unique=False)
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_message_id'), 'reaction', ['message_id'], unique=False)
    op.create_index(op.f('ix_reaction_user_id'), 'reaction', ['user_id'], unique=False)
    op.drop_table('userprofile')
    op.add_column('user', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'display_name')
    op.create_table('userprofile',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('icon_url', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_reaction_user_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_message_id'), table_name='reaction')
    op.drop_table('reaction')
    op.drop_index('ix_message_thread_root_id_created_at', table_name='message')
    op.drop_index('ix_message_parent_id', table_name='message')
    op.drop_index('ix_message_channel_id_created_at', table_name='message')
    op.drop_index(op.f('ix_message_author_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_follow_user_id'), table_name='follow')
    op.drop_index(op.f('ix_follow_channel_id'), table_name='follow')
    op.drop_table('follow')
    op.drop_index(op.f('ix_channelmember_user_id'), table_name='channelmember')
    op.drop_index(op.f('ix_channelmember_channel_id'), table_name='channelmember')
    op.drop_table('channelmember')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_channel_slug'), table_name='channel')
    op.drop_index(op.f('ix_channel_owner_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
