"""Add Channel, Message, and related tables

Revision ID: 8f257ee5497b
Revises: 055e30a3ea0a
Create Date: 2025-11-26 03:39:49.854004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f257ee5497b'
down_revision: Union[str, Sequence[str], None] = '055e30a3ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_owner_id'), 'channel', ['owner_id'], unique=False)
    op.create_index(op.f('ix_channel_slug'), 'channel', ['slug'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('channelmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channelmember_channel_user')
    )
    op.create_index(op.f('ix_channelmember_channel_id'), 'channelmember', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channelmember_user_id'), 'channelmember', ['user_id'], unique=False)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_follow_user_channel')
    )
    op.create_index(op.f('ix_follow_channel_id'), 'follow', ['channel_id'], unique=False)
    op.create_index(op.f('ix_follow_user_id'), 'follow', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('thread_root_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['thread_root_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_author_id'), 'message', ['author_id'], unique=False)
    op.create_index(op.f('ix_message_channel_id'), 'message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_parent_id'), 'message', ['parent_id'], unique=False)
    op.create_index(op.f('ix_message_thread_root_id'), 'message', ['thread_root_id'], unique=False)
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'type', name='uq_reaction_message_user_type')
    )
    op.create_index(op.f('ix_reaction_message_id'), 'reaction', ['message_id'], unique=False)
    op.create_index(op.f('ix_reaction_user_id'), 'reaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_user_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_message_id'), table_name='reaction')
    op.drop_table('reaction')
    op.drop_index(op.f('ix_message_thread_root_id'), table_name='message')
    op.drop_index(op.f('ix_message_parent_id'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index(op.f('ix_message_channel_id'), table_name='message')
    op.drop_index(op.f('ix_message_author_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_follow_user_id'), table_name='follow')
    op.drop_index(op.f('ix_follow_channel_id'), table_name='follow')
    op.drop_table('follow')
    op.drop_index(op.f('ix_channelmember_user_id'), table_name='channelmember')
    op.drop_index(op.f('ix_channelmember_channel_id'), table_name='channelmember')
    op.drop_table('channelmember')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_channel_slug'), table_name='channel')
    op.drop_index(op.f('ix_channel_owner_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
