"""Add unique constraints and indexes to models

Revision ID: f37489e4e2de
Revises: 769d596e6c7e
Create Date: 2025-11-26 00:20:26.707127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f37489e4e2de'
down_revision: Union[str, Sequence[str], None] = '769d596e6c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_channelmember_channel_user', 'channelmember', ['channel_id', 'user_id'])
    op.create_unique_constraint('uq_follow_user_channel', 'follow', ['user_id', 'channel_id'])
    op.create_index('ix_notification_user_id_created_at', 'notification', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notification_user_id_read_at', 'notification', ['user_id', 'read_at'], unique=False)
    op.create_unique_constraint('uq_reaction_message_user_type', 'reaction', ['message_id', 'user_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reaction_message_user_type', 'reaction', type_='unique')
    op.drop_index('ix_notification_user_id_read_at', table_name='notification')
    op.drop_index('ix_notification_user_id_created_at', table_name='notification')
    op.drop_constraint('uq_follow_user_channel', 'follow', type_='unique')
    op.drop_constraint('uq_channelmember_channel_user', 'channelmember', type_='unique')
    # ### end Alembic commands ###
